const cars = [
    new Vehicle(
        "AU-001",
        "../../img/cars/audi/a6.png",
        "Audi",
        "A6",
        "Premium",
        "1 large, 2 small luggages",
        5,
        70,
        7.5,
        200
    ),
    new Vehicle(
        "AU-002",
        "../../img/cars/audi/q7.png",
        "Audi",
        "Q7",
        "SUV",
        "2 large, 2 small luggages",
        7,
        75,
        8.5,
        225
    ),
    new Vehicle(
        "BMW-001",
        "../../img/cars/bmw/318i.png",
        "BMW",
        "318i",
        "Premium",
        "1 large, 2 small luggages",
        5,
        60,
        7.0,
        200
    ),
    new Vehicle(
        "BMW-002",
        "../../img/cars/bmw/520i.png",
        "BMW",
        "520i",
        "Premium",
        "1 large, 2 small luggages",
        5,
        70,
        7.5,
        200
    ),
    new Vehicle(
        "BMW-003",
        "../../img/cars/bmw/x3.png",
        "BMW",
        "X3",
        "SUV",
        "2 large, 2 small luggages",
        5,
        70,
        8.0,
        180
    ),
    new Vehicle(
        "CHV-001",
        "../../img/cars/chevrolet/camaro.png",
        "Chevrolet",
        "Camaro",
        "Premium",
        "1 large, 2 small luggages",
        2,
        60,
        6.5,
        300
    ),
    new Vehicle(
        "CHV-002",
        "../../img/cars/chevrolet/monza.png",
        "Chevrolet",
        "Monza",
        "Premium",
        "1 large, 2 small luggages",
        5,
        60,
        7.0,
        200
    ),
    new Vehicle(
        "CHV-003",
        "../../img/cars/chevrolet/onix.png",
        "Chevrolet",
        "Onix",
        "Premium",
        "1 large, 2 small luggages",
        5,
        50,
        6.0,
        200
    ),
    new Vehicle(
        "FRD-001",
        "../../img/cars/ford/mondeo.png",
        "Ford",
        "Mondeo",
        "Premium",
        "1 large, 2 small luggages",
        5,
        66,
        6.76,
        200
    ),
    new Vehicle(
        "FRD-002",
        "../../img/cars/ford/everest.png",
        "Ford",
        "Everest",
        "SUV",
        "2 large, 2 small luggages",
        7,
        80,
        9.0,
        225
    ),
    new Vehicle(
        "FRD-003",
        "../../img/cars/ford/explorer.png",
        "Ford",
        "Explorer",
        "SUV",
        "2 large, 2 small luggages",
        7,
        90,
        9.5,
        225
    ),
    new Vehicle(
        "HON-001", 
        "../../img/cars/honda/city.png", 
        "Honda", 
        "City", 
        "Standard", 
        "1 large, 1 small luggage", 
        5, 
        40, 
        5.6, 
        100.00
    ),
    new Vehicle(
        "HON-002", 
        "../../img/cars/honda/civic.png", 
        "Honda", 
        "Civic", 
        "Standard", 
        "1 large, 1 small luggage", 
        5, 
        45, 
        6.0, 
        100.00
    ),
    new Vehicle(
        "HON-003",
        "../../img/cars/honda/vezel.png",
        "Honda",
        "Vezel",
        "SUV",
        "2 large, 2 small luggages",
        5,
        50,
        6.5,
        180
    ),
    new Vehicle(
        "KIA-001",
        "../../img/cars/kia/optima.png",
        "Kia",
        "Optima",
        "Standard",
        "1 large, 2 small luggages",
        5,
        50,
        6.0,
        100
    ),
    new Vehicle(
        "LEX-001",
        "../../img/cars/lexus/RX300.png",
        "Lexus",
        "RX300",
        "SUV",
        "2 large, 2 small luggages",
        5,
        70,
        8.0,
        180
    ),
    new Vehicle(
        "LEX-002",
        "../../img/cars/lexus/ES250.png",
        "Lexus",
        "ES250",
        "Premium",
        "1 large, 2 small luggages",
        5,
        70,
        7.5,
        200
    ),
    new Vehicle(
        "MAZ-001",
        "../../img/cars/mazda/3.png",
        "Mazda",
        "3",
        "Standard",
        "1 large, 1 small luggage",
        5,
        40,
        5.6,
        100
    ),
    new Vehicle(
        "MAZ-002",
        "../../img/cars/mazda/CX-5.png",
        "Mazda",
        "CX-5",
        "SUV",
        "2 large, 2 small luggages",
        5,
        60,
        7.0,
        180        
    ),
    new Vehicle(
        "MBZ-001",
        "../../img/cars/mercedes/C180.png",
        "Mercedes",
        "C180",
        "Premium",
        "1 large, 2 small luggages",
        5,
        70,
        7.5,
        200
    ),
    new Vehicle(
        "MIT-001",
        "../../img/cars/mitsubishi/lancerEX.png",
        "Mitsubishi",
        "Lancer EX",
        "Standard",
        "1 large, 1 small luggage",
        5,
        40,
        5.6,
        100
    ),
    new Vehicle(
        "NIS-001",
        "../../img/cars/nissan/x-trail.png",
        "Nissan",
        "X-Trail",
        "SUV",
        "2 large, 2 small luggages",
        5,
        60,
        7.0,
        180
    ),
    new Vehicle(
        "NIS-002",
        "../../img/cars/nissan/sylphy.png",
        "Nissan",
        "Sylphy",
        "Standard",
        "1 large, 1 small luggage",
        5,
        40,
        5.6,
        100
    ),
    new Vehicle(
        "NIS-003",
        "../../img/cars/nissan/qashqai.png",
        "Nissan",
        "Qashqai",
        "SUV",
        "2 large, 2 small luggages",
        5,
        50,
        6.5,
        180
    ),
    new Vehicle(
        "OPL-001",
        "../../img/cars/opel/mokka.png",
        "Opel",
        "Mokka",
        "SUV",
        "2 large, 2 small luggages",
        5,
        50,
        6.5,
        180

    ),
    new Vehicle(
        "SUZ-001",
        "../../img/cars/suzuki/ertiga.png",
        "Suzuki",
        "Ertiga",
        "SUV",
        "2 large, 2 small luggages",
        7,
        50,
        6.5,
        180
    ),
    new Vehicle(
        "TYT-001", 
        "../../img/cars/toyota/prius.png", 
        "Toyota", 
        "Prius", 
        "Standard", 
        "1 large, 2 small luggages", 
        5, 
        43, 
        4.1, 
        100.00
    ),
    new Vehicle(
        "TYT-002",
        "../../img/cars/toyota/altis.png",
        "Toyota",
        "Altis",
        "Standard",
        "1 large, 1 small luggage",
        5,
        45,
        6.0,
        100
    ),
    new Vehicle(
        "TYT-003",
        "../../img/cars/toyota/yaris_cross.png",
        "Toyota",
        "Yaris Cross",
        "SUV",
        "2 large, 2 small luggages",
        5,
        50,
        6.5,
        180
    ),
    new Vehicle(
        "TYT-004",
        "../../img/cars/toyota/vios.png",
        "Toyota",
        "Vios",
        "Standard",
        "1 large, 1 small luggage",
        5,
        40,
        5.6,
        100
    ),
    new Vehicle(
        "VOL-001",
        "../../img/cars/volkswagen/arteon.png",
        "Volkswagen",
        "Arteon",
        "Premium",
        "1 large, 2 small luggages",
        5,
        70,
        7.5,
        200
    ),
];
